# Generated by Django 2.2 on 2022-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text_news', models.TextField(max_length=2000, verbose_name='Текст новости')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
