# Generated by Django 2.2 on 2022-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_add',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
