# Generated by Django 2.2 on 2022-11-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_news', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='add_news.Articles'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
