# Generated by Django 2.2 on 2022-11-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_news', '0005_auto_20221102_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='activity',
            field=models.BooleanField(default=True),
        ),
    ]
