# Generated by Django 3.1.4 on 2022-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_news', '0006_articles_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('a', 'activity')], default='a', max_length=5),
        ),
    ]
