# Generated by Django 3.1.4 on 2022-11-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_news', '0007_articles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('a', 'activity'), ('d', 'delete')], default='a', max_length=5),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('a', 'activity'), ('d', 'delete')], default='a', max_length=5),
        ),
    ]
